- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 3600
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10800
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 65
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorOfficer
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    outerClothing: ClothingOuterVestArmorSec # Corvax-Resprite
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22
    underwearb: ClothingUnderwearBottomBoxersWhite # IanStation
  underweart: ClothingUnderwearTopWhite # IanStation
  underwearb: ClothingUnderwearBottomPantiesWhite # IanStation
  innerClothingSkirt: ClothingUniformJumpskirtSeniorOfficer
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
