- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    underwearb: ClothingUnderwearBottomBoxersWhite # IanStation
  underweart: ClothingUnderwearTopWhite # IanStation
  underwearb: ClothingUnderwearBottomPantiesWhite # IanStation
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
    underwearb: ClothingUnderwearBottomBoxersWhite # IanStation
  underweart: ClothingUnderwearTopWhite # IanStation
  underwearb: ClothingUnderwearBottomPantiesWhite # IanStation
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricord
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
    underwearb: ClothingUnderwearBottomBoxersWhite # IanStation
  underweart: ClothingUnderwearTopWhite # IanStation
  underwearb: ClothingUnderwearBottomPantiesWhite # IanStation
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
